name: Silver Spear Gin
favicon: null
layout_spectrum: 0.68508
typography_spectrum: 0.65599
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfd'
    - '#afa69d'
    - '#000005'
    - '#222831'
    - '#55555d'
  brandStrength: 0.16667791210084393
  lightness: 0.9428808945160261
  saturation: 0.48407955518006496
  rhythmicContrast: 0.007541340154876175
purpose:
  - name: null
    item: null
    url: null
